/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otaviosonnenstrahl;

/**
 *
 * @author PC
 */
public class TelaSuperCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaSuperCalculadora
     */
    public TelaSuperCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltxtTitulo = new javax.swing.JLabel();
        lbltxtValor = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lbltxtResto = new javax.swing.JLabel();
        lbltxtCubo = new javax.swing.JLabel();
        lbltxtRaizQuadrada = new javax.swing.JLabel();
        lbltxtRaizCubica = new javax.swing.JLabel();
        lbltxtValorAbsoluto = new javax.swing.JLabel();
        lblresResto = new javax.swing.JLabel();
        lblresCubo = new javax.swing.JLabel();
        lblresRaizQuadrada = new javax.swing.JLabel();
        lblresRaizCubica = new javax.swing.JLabel();
        lblresValorAbsoluto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltxtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltxtTitulo.setText("Super Calculadora");

        lbltxtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltxtValor.setText("Informe um Valor:");

        spnValor.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculadora.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbltxtResto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltxtResto.setText("Resto Divisao por 2:");

        lbltxtCubo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltxtCubo.setText("Elevado ao Cubo:");

        lbltxtRaizQuadrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltxtRaizQuadrada.setText("Raiz Quadrada:");

        lbltxtRaizCubica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltxtRaizCubica.setText("Raiz Cubica");

        lbltxtValorAbsoluto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltxtValorAbsoluto.setText("Valor Absoluto:");

        lblresResto.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblresResto.setForeground(new java.awt.Color(102, 102, 255));
        lblresResto.setText("0");

        lblresCubo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblresCubo.setForeground(new java.awt.Color(102, 102, 255));
        lblresCubo.setText("0");

        lblresRaizQuadrada.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblresRaizQuadrada.setForeground(new java.awt.Color(102, 102, 255));
        lblresRaizQuadrada.setText("0");

        lblresRaizCubica.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblresRaizCubica.setForeground(new java.awt.Color(102, 102, 255));
        lblresRaizCubica.setText("0");

        lblresValorAbsoluto.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblresValorAbsoluto.setForeground(new java.awt.Color(102, 102, 255));
        lblresValorAbsoluto.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lbltxtTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltxtValorAbsoluto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblresValorAbsoluto))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltxtRaizCubica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblresRaizCubica))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltxtRaizQuadrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblresRaizQuadrada))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltxtCubo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblresCubo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltxtResto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblresResto))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbltxtValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltxtTitulo)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtValor)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtResto)
                    .addComponent(lblresResto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtCubo)
                    .addComponent(lblresCubo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtRaizQuadrada)
                    .addComponent(lblresRaizQuadrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtRaizCubica)
                    .addComponent(lblresRaizCubica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtValorAbsoluto)
                    .addComponent(lblresValorAbsoluto))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int Valor = Integer.parseInt(spnValor.getValue().toString());
        
        //Resto por 2
        int ResultadoResto = Valor % 2;
        lblresResto.setText(Integer.toString(ResultadoResto));
        // Elevado ao Cubo
        double ResultadoCubo = Math.pow(Valor, 3);
        lblresCubo.setText(String.format("%.2f", ResultadoCubo));
        // Raiz Quadrada
        double ResultadoRaizQuadrada = Math.sqrt(Valor);
        lblresRaizQuadrada.setText(String.format("%.2f", ResultadoRaizQuadrada));
        // Raiz Cubica
        double ResultadoRaizCubica = Math.cbrt(Valor);
        lblresRaizCubica.setText(String.format("%.2f", ResultadoRaizCubica));
        // Valor Absoluto
        lblresValorAbsoluto.setText(Integer.toString(Valor));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSuperCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblresCubo;
    private javax.swing.JLabel lblresRaizCubica;
    private javax.swing.JLabel lblresRaizQuadrada;
    private javax.swing.JLabel lblresResto;
    private javax.swing.JLabel lblresValorAbsoluto;
    private javax.swing.JLabel lbltxtCubo;
    private javax.swing.JLabel lbltxtRaizCubica;
    private javax.swing.JLabel lbltxtRaizQuadrada;
    private javax.swing.JLabel lbltxtResto;
    private javax.swing.JLabel lbltxtTitulo;
    private javax.swing.JLabel lbltxtValor;
    private javax.swing.JLabel lbltxtValorAbsoluto;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
