/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author PC
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        lblTextoBalao.setText("<html>Vou pensar em um numero de <strong>1 a 5</strong> tente adivinhar</html>");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoBalao = new javax.swing.JLabel();
        imgBalaoTexto = new javax.swing.JLabel();
        lblNomeAtividade = new javax.swing.JLabel();
        imgGenio = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoBalao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextoBalao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoBalao.setText("jLabel2");
        lblTextoBalao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblTextoBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 100));

        imgBalaoTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bate-papo.png"))); // NOI18N
        getContentPane().add(imgBalaoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        lblNomeAtividade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeAtividade.setText("ATIVIDADE 8 - OTAVIO SONNENSTRAHL");
        getContentPane().add(lblNomeAtividade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        imgGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/225px-Genie_KHII.png"))); // NOI18N
        getContentPane().add(imgGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        txtValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtValor.setText("Valor:");
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 60, 20));

        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 50, 20));

        jButton1.setText("Palpite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double n = 1 + Math.random() * (6-1);
        int valor = (int) n;
        System.out.println(valor);
        
         int num = Integer.parseInt(spnValor.getValue().toString());
         
         String f1 = "ACERTOU";
         String f2 = "<html>ERROU!! o valor era: " + valor + "</html>";
         
         String res = (valor == num)?f1:f2;
         
         lblTextoBalao.setText(res);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBalaoTexto;
    private javax.swing.JLabel imgGenio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblNomeAtividade;
    private javax.swing.JLabel lblTextoBalao;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
